2021-07-27 01:47:54,793, ERROR, root, Бот упал с ошибкой: list index out of range
Traceback (most recent call last):
  File "/mnt/c/Dev/api_sp1_bot-1/homework.py", line 103, in main
    homework = homeworks['homeworks'][0]
IndexError: list index out of range
2021-07-27 01:47:54,804, INFO, root, Бот отправил сообщение Бот упал с ошибкой: list index out of range
2021-07-27 02:44:25,705, ERROR, root, Бот упал с ошибкой: local variable 'homework' referenced before assignment
Traceback (most recent call last):
  File "/mnt/c/Dev/api_sp1_bot-1/homework.py", line 108, in main
    message = parse_homework_status(homework)
UnboundLocalError: local variable 'homework' referenced before assignment
2021-07-27 02:44:25,714, INFO, root, Бот отправил сообщение Бот упал с ошибкой: local variable 'homework' referenced before assignment
